Repository compilers-uff/lexer-e-parser-grupo-11, pull requests merged in 2025-04, with the labels that each got.

#6 JFlex léxico parte das STRINGS.
  src/main/java/chocopy/pa1/StudentParser.java
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
Labels: Add

#7 Adiciona a lógica de INDENT e DEDENT no arquivo JFlex
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
Labels: Add

#8 Adição do README.MD atualizado
  README.md
Labels: documentation

#10 Fixes para a Identação no arquivo JFlex
  src/main/java/chocopy/pa1/StudentParser.java
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
Labels: bug

#14 Remoção dos símbolos não utilizados
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/student_contributed/good.py
Labels: bug
